# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todos',
            old_name='complete',
            new_name='completed',
        ),
    ]
